runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
